### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by kawasaki** [python-sdbus/python-sdbus-bluez#7]
Hi @igo95862 

I'm working on a project [pyscrlink](https://github.com/kawasaki/pyscrlink). It uses a python library called "bluepy" to communicate with Bluetooth devices. However, bluepy is unstable these days. I would like to switch from bluepy to python-sdbus and python-sdbus-bluez. I have prototyped it and it looks working well: [ref](https://github.com/kawasaki/pyscrlink/tree/dbus2).

pyscrlink is now shared through PyPI. To make pyscrlink work with python-sdbus and python-sdbus-bluez, they must be released through PyPI also. I can find python-sdbus on PyPI, but can not find python-sdbus-bluez.

Do you have plan to release python-sdbus-bluze on PyPI?

**Comment by igo95862** [comment]
Hello @kawasaki 

The issue is that I don't have that much time to refine the Bluez binds. This is further exacerbated by the fact that Bluez does not provide an easy way to access D-Bus introspection. See: https://github.com/bluez/bluez/issues/296

Without introspection every interface would need to be created and checked by hand and I don't have this much time to work on it. 

That I would recommend for now is having a copy of the interfaces within your source tree.

**Comment by kawasaki** [comment]
@igo95862 Thanks for the swift response and sharing current status. Per your recommendation, I will copy python-sdbus-bluez to my project. I will respect its license and your authorship. Thanks!
